# Generated by Django 3.1.dev20191030155240 on 2019-11-02 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsite1app1', '0002_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slag', models.SlugField()),
                ('dercription', models.ImageField(upload_to='')),
                ('image', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('availible', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsite1app1.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsite1app1.Category')),
            ],
        ),
    ]
