# Generated by Django 3.1.dev20191030155240 on 2019-11-03 01:24

from django.db import migrations, models
import newsite1app1.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsite1app1', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slag',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='dercription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=newsite1app1.models.image_folder),
        ),
    ]
