# Generated by Django 3.1.dev20191030155240 on 2019-11-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsite1app1', '0004_auto_20191103_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dercription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
