# Generated by Django 3.1.dev20191030155240 on 2019-11-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsite1app1', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='newsite1app1.CartItem'),
        ),
    ]
