# Generated by Django 3.1.dev20191030155240 on 2019-11-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsite1app1', '0008_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')], default='Самовывоз', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Принят в обработку', 'Принят в обработку'), ('Выполняется', 'Выполняется'), ('Оплачен', 'Оплачен')], max_length=100),
        ),
    ]
